/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.109
 * Generated at: 2022-03-10 09:23:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._03_002d10;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _08_005f05_005f02_005fform04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Form Processing</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>회원가입</h3>\r\n");
      out.write("\t<form action=\"08_05_02_form04_process.jsp\" name=\"member\" method=\"post\">\r\n");
      out.write("\t\t<p>\t아이디 : <input type=\"text\" name=\"id\"> <input type=\"button\"\tvalue=\"아이디 중복검사\">\r\n");
      out.write("\t\t<p>\t비밀번호 : <input type=\"password\" name=\"passwd\">\r\n");
      out.write("\t\t<p>\t이름 : <input type=\"text\" name=\"name\">\r\n");
      out.write("\t\t<p>\t연락처 : <select name=\"phone1\">\r\n");
      out.write("\t\t\t\t<option value=\"010\" selected>010</option>\r\n");
      out.write("\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t</select> - <input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone2\"> -\r\n");
      out.write("\t\t\t<input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone3\">\r\n");
      out.write("\t\t<p>\t성별 : <input type=\"radio\" name=\"sex\" value=\"남성\" checked>남성 \r\n");
      out.write("\t\t\t\t<input\ttype=\"radio\" name=\"sex\" value=\"여성\">여성\r\n");
      out.write("\t\t<p>\t취미 : 독서<input type=\"checkbox\" name=\"hobby\" value=\"독서\" checked>\r\n");
      out.write("\t\t\t\t운동<input type=\"checkbox\" name=\"hobby\" value=\"운동\"> \r\n");
      out.write("\t\t\t\t영화<input type=\"checkbox\" name=\"hobby\" value=\"영화\">\r\n");
      out.write("\t\t<p>\t<textarea name=\"comment\" cols=\"30\" rows=\"3\"\tplaceholder=\"가입인사를 입력해주세요\"></textarea>\r\n");
      out.write("\t\t<p>\t<input type=\"submit\" value=\"가입하기\"> \r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
